### ISSUE TITLE
Use without Symfony? Can't find Class

### ISSUE THREAD

**Issue by coxoperationsengineer** [twigphp/string-extra#1]
Hello,

I am attempting to use this with a Twig 3.0 standalone project, and I can't seem to get it working, is it supported?  When I did $ composer req twig/string-extra, it installed under the following tree structure, and I am trying to use it as the documentation suggested https://twig.symfony.com/doc/3.x/filters/u.html.

    use  Twig\Extra\String\StringExtension;

    $twig  =  new  \Twig\Environment($loader,  [
        'debug'  =>  true,
        'auto_reload'  =>  true,
        'strict_variables'  =>  false,
    ]);
    $twig->addExtension(new  \Twig\Extension\DebugExtension());
    $twig->addExtension(new  StringExtension());
    
    ├── bin
    ├── composer
    ├── symfony
    │   ├── polyfill-ctype
    │   ├── polyfill-intl-grapheme
    │   ├── polyfill-intl-normalizer
    │   │   └── Resources
    │   │       ├── stubs
    │   │       └── unidata
    │   ├── polyfill-mbstring
    │   │   └── Resources
    │   │       └── unidata
    │   ├── string
    │   │   ├── Exception
    │   │   ├── Resources
    │   │   └── Slugger
    │   └── translation-contracts
    │       └── Test
    └── twig
        ├── string-extra
        │   └── src
        └── twig
            ├── doc
            │   ├── filters
            │   ├── functions
            │   ├── tags
            │   └── tests
            └── src
                ├── Cache
                ├── Error
                ├── Extension
                ├── Loader
                ├── Node
                │   └── Expression
                │       ├── Binary
                │       ├── Filter
                │       ├── Test
                │       └── Unary
                ├── NodeVisitor
                ├── Profiler
                │   ├── Dumper
                │   ├── Node
                │   └── NodeVisitor
                ├── RuntimeLoader
                ├── Sandbox
                ├── Test
                ├── TokenParser
                └── Util

**Comment by nicolas-grekas** [comment]
Sorry but "it does not work" is not an actionable description of your issue.
Please describe how it fails, what you would expect but behaves differently - and how.
Please provide reproducing steps as much as possible.
